ALTER TABLE nodes
    ADD COLUMN IF NOT EXISTS config_version BIGINT NOT NULL DEFAULT 1 CHECK (config_version > 0),
    ADD COLUMN IF NOT EXISTS cpu_percent DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (cpu_percent BETWEEN 0 AND 100),
    ADD COLUMN IF NOT EXISTS memory_percent DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (memory_percent BETWEEN 0 AND 100),
    ADD COLUMN IF NOT EXISTS load_one DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (load_one >= 0),
    ADD COLUMN IF NOT EXISTS active_connections BIGINT NOT NULL DEFAULT 0 CHECK (active_connections >= 0),
    ADD COLUMN IF NOT EXISTS bytes_in BIGINT NOT NULL DEFAULT 0 CHECK (bytes_in >= 0),
    ADD COLUMN IF NOT EXISTS bytes_out BIGINT NOT NULL DEFAULT 0 CHECK (bytes_out >= 0);

